const characters = [
  {_id: 1, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/CL.png'},
  {_id: 2, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/TL.png'},
  {_id: 3, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/DT.png'},
  {_id: 4, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/V.png'},
  {_id: 5, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/KD.png'},
  {_id: 6, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/MT.png'},
  {_id: 7, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/Mel.png'},
  {_id: 8, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/OT.png'},
  {_id: 9, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/ES.png'},
  {_id: 10, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/HS.png'},
  {_id: 11, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/Ned.png'},
  {_id: 12, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/RB.png'},
  {_id: 13, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/JS.png'},
  {_id: 14, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/CS.png'},
  {_id: 15, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/PB.png'},
  {_id: 16, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/SC.png'},
  {_id: 17, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/SS.png'},
  {_id: 18, image: 'https://raw.githubusercontent.com/markieruiz/clickyGame/master/public/images/AS.png'}

  // {_id: 2, image: "TL.png"},
  // {_id: 3, image: 'DT.png'},
  // {_id: 4, image: 'V.png'},
  // {_id: 5, image: 'KD.png'},
  // {_id: 6, image: 'MT.png'},
  // {_id: 7, image: 'Mel.png'},
  // {_id: 8, image: 'OT.png'},
  // {_id: 9, image: 'ES.png'},
  // {_id: 10, image: 'HS.png'},
  // {_id: 11, image: 'Ned.png'},
  // {_id: 12, image: 'RB.png'},
  // {_id: 13, image: 'JS.png'},
  // {_id: 14, image: 'CS.png'},
  // {_id: 15, image: 'PB.png'},
  // {_id: 16, image: 'SC.png'},
  // {_id: 17, image: 'SS.png'},
  // {_id: 18, image: 'AS.png'}
]

export default characters
